let data = {
  officerData: [
    {
      onDuty: 1,
      offDuty: 0,
      id: 1,
      command: {commandName: '006 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 2,
      command: {commandName: '006 DET SQUAD'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 3,
      command: {commandName: '001 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 4,
      command: {commandName: '007 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 5,
      command: {commandName: '005 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 9,
      offDuty: 0,
      id: 6,
      command: {commandName: '009 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 12,
      offDuty: 0,
      id: 7,
      command: {commandName: '010 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 8,
      command: {commandName: '017 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 9,
      command: {commandName: '013 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 1,
      id: 10,
      command: {commandName: '014 PCT-MIDTOWN SO. PCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 11,
      command: {commandName: '019 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 12,
      command: {commandName: '018 PCT-MIDTOWN NO. PCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 13,
      command: {commandName: '020 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 14,
      command: {commandName: '020 DET SQUAD'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 15,
      command: {commandName: '020 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 15,
      offDuty: 1,
      id: 16,
      command: {commandName: '023 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 17,
      command: {commandName: '024 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 9,
      offDuty: 0,
      id: 18,
      command: {commandName: '025 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 19,
      command: {commandName: '026 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 20,
      command: {commandName: '024 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 21,
      command: {commandName: '028 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 10,
      offDuty: 0,
      id: 22,
      command: {commandName: '028 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 23,
      command: {commandName: '028 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 7,
      offDuty: 0,
      id: 24,
      command: {commandName: '030 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 25,
      command: {commandName: '032 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 16,
      offDuty: 0,
      id: 26,
      command: {commandName: '033 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 27,
      command: {commandName: '033 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 28,
      command: {commandName: '034 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 29,
      command: {commandName: '040 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 20,
      offDuty: 0,
      id: 30,
      command: {commandName: '040 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 31,
      command: {commandName: '041 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 32,
      command: {commandName: '042 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 33,
      command: {commandName: '042 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 34,
      command: {commandName: '041 PRECINCT'},
      injuryType: {type: 'MOS Killed or Shot'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 35,
      command: {commandName: '043 DET SQUAD'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 36,
      command: {commandName: '043 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 12,
      offDuty: 0,
      id: 37,
      command: {commandName: '043 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 38,
      command: {commandName: '043 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 39,
      command: {commandName: '044 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 19,
      offDuty: 0,
      id: 40,
      command: {commandName: '044 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 41,
      command: {commandName: '045 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 42,
      command: {commandName: '045 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 43,
      command: {commandName: '046 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 20,
      offDuty: 0,
      id: 44,
      command: {commandName: '046 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 45,
      command: {commandName: '047 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 14,
      offDuty: 1,
      id: 46,
      command: {commandName: '047 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 47,
      command: {commandName: '047 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 48,
      command: {commandName: '047 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 49,
      command: {commandName: '048 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 50,
      command: {commandName: '048 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 51,
      command: {commandName: '049 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 52,
      command: {commandName: '049 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 53,
      command: {commandName: '050 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 54,
      command: {commandName: '050 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 55,
      command: {commandName: '052 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 12,
      offDuty: 4,
      id: 56,
      command: {commandName: '052 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 57,
      command: {commandName: '052 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 58,
      command: {commandName: '060 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 59,
      command: {commandName: '060 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 10,
      offDuty: 0,
      id: 60,
      command: {commandName: '061 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 61,
      command: {commandName: '061 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 62,
      command: {commandName: '061 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 63,
      command: {commandName: '062 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 64,
      command: {commandName: '063 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 65,
      command: {commandName: '066 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 66,
      command: {commandName: '063 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 10,
      offDuty: 0,
      id: 67,
      command: {commandName: '067 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 17,
      offDuty: 1,
      id: 68,
      command: {commandName: '068 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 69,
      command: {commandName: '069 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 0,
      offDuty: 1,
      id: 70,
      command: {commandName: '070 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 13,
      offDuty: 0,
      id: 71,
      command: {commandName: '070 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 9,
      offDuty: 0,
      id: 72,
      command: {commandName: '071 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 73,
      command: {commandName: '071 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 11,
      offDuty: 0,
      id: 74,
      command: {commandName: '072 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 75,
      command: {commandName: '073 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 76,
      command: {commandName: '073 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 9,
      offDuty: 0,
      id: 77,
      command: {commandName: '073 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 78,
      command: {commandName: '075 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 79,
      command: {commandName: '075 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 19,
      offDuty: 0,
      id: 80,
      command: {commandName: '075 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 81,
      command: {commandName: '076 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 13,
      offDuty: 1,
      id: 82,
      command: {commandName: '077 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 83,
      command: {commandName: '078 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 84,
      command: {commandName: '079 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 85,
      command: {commandName: '079 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 86,
      command: {commandName: '081 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 12,
      offDuty: 0,
      id: 87,
      command: {commandName: '083 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 88,
      command: {commandName: '084 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 89,
      command: {commandName: '084 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 90,
      command: {commandName: '088 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 91,
      command: {commandName: '090 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 92,
      command: {commandName: '094 DET SQUAD'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 93,
      command: {commandName: '094 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 94,
      command: {commandName: '100 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 95,
      command: {commandName: '100 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 7,
      offDuty: 0,
      id: 96,
      command: {commandName: '101 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 97,
      command: {commandName: '101ST DET SQUAD'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 98,
      command: {commandName: '102 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 99,
      command: {commandName: '102 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 100,
      command: {commandName: '103 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 101,
      command: {commandName: '103 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 19,
      offDuty: 0,
      id: 102,
      command: {commandName: '103 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 103,
      command: {commandName: '103 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 104,
      command: {commandName: '104 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 12,
      offDuty: 0,
      id: 105,
      command: {commandName: '105 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 106,
      command: {commandName: '106 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 107,
      command: {commandName: '107 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 110,
      command: {commandName: '110 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 14,
      offDuty: 0,
      id: 117,
      command: {commandName: '113 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 123,
      command: {commandName: '120 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 125,
      command: {commandName: '121 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 132,
      command: {commandName: 'DET BORO BX HOMICIDE SQ'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 136,
      command: {commandName: 'EMER SERV UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 141,
      command: {commandName: 'HIGHWAY UNIT NO 3'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 7,
      offDuty: 0,
      id: 148,
      command: {commandName: 'HOUSING PSA 6'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 153,
      command: {commandName: 'INTEL-CRIMINAL INTEL SECTION'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 158,
      command: {commandName: 'NARC BORO BROOKLYN NORTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 163,
      command: {commandName: 'PATROL BORO STATEN ISLAND'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 169,
      command: {commandName: 'PBQN SCHOOL SAFETY'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 173,
      command: {commandName: 'QNS COURT SECTION'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 180,
      command: {commandName: 'TRANSIT BORO BX/QNS TASK FORCE'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 183,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 1'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 190,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 20'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 193,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 30'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 199,
      command: {commandName: 'TRB BRONX TRAFFIC ENF UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 11,
      offDuty: 0,
      id: 205,
      command: {commandName: '019 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 112,
      command: {commandName: '110 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 115,
      command: {commandName: '112 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 120,
      command: {commandName: '115 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 127,
      command: {commandName: '123 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 131,
      command: {commandName: 'CHIEF OF DEPT INV REVIEW SECT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 137,
      command: {commandName: 'GANG SQUAD MANHATTAN SOUTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 142,
      command: {commandName: 'HOMELESS OUTREACH UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 12,
      offDuty: 0,
      id: 146,
      command: {commandName: 'HOUSING PSA 5'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 150,
      command: {commandName: 'HOUSING PSA 7'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 155,
      command: {commandName: 'MTN SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 160,
      command: {commandName: 'NARC BORO QUEENS NORTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 165,
      command: {commandName: 'PBBN SCHOOL SAFETY'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 170,
      command: {commandName: 'PBMN SCHOOL SAFETY'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 174,
      command: {commandName: 'STRATEGIC RESP GRP 1 MANHATTAN'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 179,
      command: {commandName: 'TRANSIT BORO BKLN TASK FORCE'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 184,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 11'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 189,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 2'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 9,
      offDuty: 0,
      id: 195,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 33'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 198,
      command: {commandName: 'TRB BRONX TRAFFIC ENF UNIT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 204,
      command: {commandName: '017 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 109,
      command: {commandName: '109 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 116,
      command: {commandName: '113 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 121,
      command: {commandName: '115TH DET SQUAD'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 128,
      command: {commandName: 'BRONX COURT SECT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 130,
      command: {commandName: 'CANINE TEAM'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 135,
      command: {commandName: 'EMER SERV SQ 10'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 140,
      command: {commandName: 'HIGHWAY UNIT NO 2'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 147,
      command: {commandName: 'HOUSING PSA 6'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 152,
      command: {commandName: 'HOUSING PSA 9'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 157,
      command: {commandName: 'NARC BORO BRONX'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 0,
      offDuty: 1,
      id: 162,
      command: {commandName: 'P C O LIAISON UNIT'},
      injuryType: {type: 'MOS Killed or Shot'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 167,
      command: {commandName: 'PBBS SCHOOL SAFETY'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 171,
      command: {commandName: 'PBQS SCHOOL SAFETY'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 177,
      command: {commandName: 'STRATEGIC RESP GRP 4 QUEENS'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 0,
      offDuty: 1,
      id: 182,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 1'},
      injuryType: {type: 'MOS Killed or Shot'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 186,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 12'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 192,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 3'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 196,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 34'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 12,
      offDuty: 0,
      id: 202,
      command: {commandName: 'WARRANT SECTION'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 206,
      command: {commandName: '020 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 111,
      command: {commandName: '110 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 114,
      command: {commandName: '111 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 13,
      offDuty: 0,
      id: 122,
      command: {commandName: '120 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 126,
      command: {commandName: '122 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 133,
      command: {commandName: 'DRUG ENFORCEMENT TASK FORCE'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 138,
      command: {commandName: 'GRAND LARCENY DIVISION'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 143,
      command: {commandName: 'HOUSING PSA 1'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 145,
      command: {commandName: 'HOUSING PSA 4'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 151,
      command: {commandName: 'HOUSING PSA 8'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 156,
      command: {commandName: 'NARC BORO BRONX'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 164,
      command: {commandName: 'PBBN SCHOOL SAFETY'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 168,
      command: {commandName: 'PBBX SCHOOL SAFETY'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 175,
      command: {commandName: 'STRATEGIC RESP GRP 2 BRONX'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 178,
      command: {commandName: 'TB ANTI TERRORISM UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 18,
      offDuty: 0,
      id: 185,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 11'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 188,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 2'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 194,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 32'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 200,
      command: {commandName: 'TRB MANHATTAN SUMMONS ENF SEC'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 10,
      offDuty: 0,
      id: 203,
      command: {commandName: '006 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 108,
      command: {commandName: '108 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 113,
      command: {commandName: '111 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 118,
      command: {commandName: '113TH DET SQUAD'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 13,
      offDuty: 0,
      id: 119,
      command: {commandName: '114 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 1,
      id: 124,
      command: {commandName: '121 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 129,
      command: {commandName: 'BROOKLYN COURT SECTION'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 134,
      command: {commandName: 'EMER SERV SQ 08'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 139,
      command: {commandName: 'GRAND LARCENY DIVISION'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 144,
      command: {commandName: 'HOUSING PSA 2'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 13,
      offDuty: 0,
      id: 149,
      command: {commandName: 'HOUSING PSA 7'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 154,
      command: {commandName: 'MAN/BX SS ZONE'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 159,
      command: {commandName: 'NARC BORO BROOKLYN SOUTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 161,
      command: {commandName: 'OFFICE CHIEF SPECIAL OPER'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 166,
      command: {commandName: 'PBBN SPECIALIZED UNITS'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 172,
      command: {commandName: 'PBSI SCHOOL SAFETY'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 176,
      command: {commandName: 'STRATEGIC RESP GRP 3 BROOKLYN'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 181,
      command: {commandName: 'TRANSIT BORO MANH TASK FORCE'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 187,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 12'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 191,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 23'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 197,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 4'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 201,
      command: {commandName: 'VICE ENFORCEMENT DIV ZONE 2'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
  ],
  subjectData: [
    {
      onDuty: 1,
      offDuty: 0,
      id: 1,
      command: {commandName: '006 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 2,
      command: {commandName: '001 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 3,
      command: {commandName: '006 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 7,
      offDuty: 0,
      id: 4,
      command: {commandName: '006 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 5,
      command: {commandName: '007 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 6,
      command: {commandName: '009 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 7,
      command: {commandName: '009 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 8,
      command: {commandName: '013 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 9,
      command: {commandName: '010 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 1,
      id: 10,
      command: {commandName: '014 PCT-MIDTOWN SO. PCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 11,
      command: {commandName: '017 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 12,
      command: {commandName: '017 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 13,
      command: {commandName: '018 PCT-MIDTOWN NO. PCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 14,
      command: {commandName: '018 PCT-MIDTOWN NO. PCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 15,
      command: {commandName: '019 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 16,
      command: {commandName: '020 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 17,
      command: {commandName: '020 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 18,
      command: {commandName: '023 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 19,
      command: {commandName: '025 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 20,
      command: {commandName: '024 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 21,
      command: {commandName: '026 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 22,
      command: {commandName: '001 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 23,
      command: {commandName: '028 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 24,
      command: {commandName: '028 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 7,
      offDuty: 0,
      id: 25,
      command: {commandName: '028 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 26,
      command: {commandName: '030 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 27,
      command: {commandName: '030 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 28,
      command: {commandName: '032 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 29,
      command: {commandName: '032 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 30,
      command: {commandName: '032 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 31,
      command: {commandName: '033 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 32,
      command: {commandName: '034 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 33,
      command: {commandName: '034 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 11,
      offDuty: 0,
      id: 34,
      command: {commandName: '034 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 12,
      offDuty: 0,
      id: 35,
      command: {commandName: '040 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 1,
      id: 36,
      command: {commandName: '041 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 37,
      command: {commandName: '041 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 38,
      command: {commandName: '042 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 39,
      command: {commandName: '042 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 40,
      command: {commandName: '043 DET SQUAD'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 12,
      offDuty: 0,
      id: 41,
      command: {commandName: '043 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 42,
      command: {commandName: '044 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 22,
      offDuty: 0,
      id: 43,
      command: {commandName: '044 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 44,
      command: {commandName: '045 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 45,
      command: {commandName: '046 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 18,
      offDuty: 0,
      id: 46,
      command: {commandName: '046 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 47,
      command: {commandName: '047 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 29,
      offDuty: 0,
      id: 48,
      command: {commandName: '047 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 49,
      command: {commandName: '048 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 50,
      command: {commandName: '048 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 51,
      command: {commandName: '050 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 52,
      command: {commandName: '052 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 10,
      offDuty: 0,
      id: 53,
      command: {commandName: '052 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 54,
      command: {commandName: '060 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 55,
      command: {commandName: '060 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 56,
      command: {commandName: '060 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 57,
      command: {commandName: '061 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 58,
      command: {commandName: '062 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 59,
      command: {commandName: '063 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 60,
      command: {commandName: '066 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 61,
      command: {commandName: '067 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 62,
      command: {commandName: '068 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 63,
      command: {commandName: '062 SCHOOL SAFETY UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 64,
      command: {commandName: '069 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 65,
      command: {commandName: '069 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 66,
      command: {commandName: '070 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 67,
      command: {commandName: '070 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 68,
      command: {commandName: '072 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 69,
      command: {commandName: '071 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 70,
      command: {commandName: '072 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 71,
      command: {commandName: '073 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 72,
      command: {commandName: '073 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 73,
      command: {commandName: '073 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 74,
      command: {commandName: '075 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 75,
      command: {commandName: '075 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 29,
      offDuty: 0,
      id: 76,
      command: {commandName: '075 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 77,
      command: {commandName: '076 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 11,
      offDuty: 0,
      id: 78,
      command: {commandName: '077 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 79,
      command: {commandName: '078 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 80,
      command: {commandName: '079 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 15,
      offDuty: 0,
      id: 81,
      command: {commandName: '079 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 82,
      command: {commandName: '081 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 83,
      command: {commandName: '081 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 84,
      command: {commandName: '083 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 9,
      offDuty: 0,
      id: 85,
      command: {commandName: '083 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 86,
      command: {commandName: '084 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 87,
      command: {commandName: '088 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 88,
      command: {commandName: '090 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 89,
      command: {commandName: '088 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 90,
      command: {commandName: '090 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 91,
      command: {commandName: '094 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 92,
      command: {commandName: '100 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 9,
      offDuty: 0,
      id: 93,
      command: {commandName: '101 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 94,
      command: {commandName: '101 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 95,
      command: {commandName: '102 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 19,
      offDuty: 0,
      id: 96,
      command: {commandName: '103 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 97,
      command: {commandName: '104 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 98,
      command: {commandName: '104 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 99,
      command: {commandName: '105 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 8,
      offDuty: 0,
      id: 100,
      command: {commandName: '105 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 101,
      command: {commandName: '106 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 7,
      offDuty: 0,
      id: 102,
      command: {commandName: '106 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 103,
      command: {commandName: '108 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 104,
      command: {commandName: '109 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 105,
      command: {commandName: '110 PRECINCT'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 106,
      command: {commandName: '110 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 107,
      command: {commandName: '110 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 111,
      command: {commandName: '115 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 114,
      command: {commandName: '122 PRECINCT'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 120,
      command: {commandName: 'DRUG ENFORCEMENT TASK FORCE'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 126,
      command: {commandName: 'EMER SERV SQ 02'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 130,
      command: {commandName: 'GANG SQUAD BROOKLYN NORTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 135,
      command: {commandName: 'HIGHWAY UNIT NO.5'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 140,
      command: {commandName: 'HOUSING PSA 6'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 145,
      command: {commandName: 'INTEL-CRIMINAL INTEL SECTION'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 149,
      command: {commandName: 'NARC BORO BRONX'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 155,
      command: {commandName: 'OFFICE CHIEF SPECIAL OPER'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 159,
      command: {commandName: 'PATROL BORO MAN SOUTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 165,
      command: {commandName: 'PBQS SPECIALIZED UNITS'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 168,
      command: {commandName: 'STRATEGIC RESP GRP 3 BROOKLYN'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 173,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 11'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 177,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 2'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 183,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 32'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 189,
      command: {commandName: 'TRB BROOKLYN TRAFFIC ENF UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 7,
      offDuty: 0,
      id: 109,
      command: {commandName: '113 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 117,
      command: {commandName: '123 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 122,
      command: {commandName: 'BKLYN SPECIAL VICTIMS SQUAD'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 125,
      command: {commandName: 'EMER SERV SQ 03'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 131,
      command: {commandName: 'HIGHWAY UNIT NO 3'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 134,
      command: {commandName: 'HOUSING PSA 2'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 141,
      command: {commandName: 'HOUSING PSA 6'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 144,
      command: {commandName: 'INTEL-CRIMINAL INTEL SECTION'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 150,
      command: {commandName: 'NARC BORO BRONX'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 154,
      command: {commandName: 'NARC BORO MANHATTAN NORTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 160,
      command: {commandName: 'OTHER'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 164,
      command: {commandName: 'PBQN SPECIALIZED UNITS'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 1,
      id: 169,
      command: {commandName: 'STRATEGIC RESP GRP 4 QUEENS'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 172,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 11'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 179,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 3'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 182,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 32'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 1,
      id: 188,
      command: {commandName: 'WARRANT SECTION'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 6,
      offDuty: 0,
      id: 112,
      command: {commandName: '121 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 7,
      offDuty: 0,
      id: 116,
      command: {commandName: '122 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 119,
      command: {commandName: 'CANINE TEAM'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 127,
      command: {commandName: 'EMER SERV SQ 05'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 133,
      command: {commandName: 'HOUSING PSA 1'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 138,
      command: {commandName: 'HOUSING PSA 5'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 142,
      command: {commandName: 'HOUSING PSA 7'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 147,
      command: {commandName: 'MAN/BX SS ZONE'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 151,
      command: {commandName: 'NARC BORO BROOKLYN NORTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 158,
      command: {commandName: 'NARC BORO STATEN ISLAND'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 163,
      command: {commandName: 'STRATEGIC RESP GRP 1 MANHATTAN'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 166,
      command: {commandName: 'STRATEGIC RESP GRP 2 BRONX'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 171,
      command: {commandName: 'TRANSIT BORO MANH TASK FORCE'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 175,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 12'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 180,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 30'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 185,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 4'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 190,
      command: {commandName: 'TRB CITYWIDE TRAFFIC T/F'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 110,
      command: {commandName: '114 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 115,
      command: {commandName: '112 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 121,
      command: {commandName: 'BRONX ROBBERY SQUAD'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 124,
      command: {commandName: 'EMER SERV UNIT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 129,
      command: {commandName: 'GANG SQUAD MANHATTAN SOUTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 5,
      offDuty: 0,
      id: 136,
      command: {commandName: 'HOUSING PSA 4'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 139,
      command: {commandName: 'HOUSING PSA 3'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 146,
      command: {commandName: 'HOUSING PSA 9'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 152,
      command: {commandName: 'NARC BORO BROOKLYN SOUTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 157,
      command: {commandName: 'PATROL BORO STATEN ISLAND'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 161,
      command: {commandName: 'PBQS SCHOOL SAFETY'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 167,
      command: {commandName: 'STRATEGIC RESP GRP 2 BRONX'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 174,
      command: {commandName: 'STRATEGIC RESP GRP 5 SI'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 178,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 20'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 184,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 33'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 187,
      command: {commandName: 'WARRANT SECTION'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 108,
      command: {commandName: '111 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 13,
      offDuty: 0,
      id: 113,
      command: {commandName: '120 PRECINCT'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 118,
      command: {commandName: 'BROOKLYN COURT SECTION'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 0,
      offDuty: 1,
      id: 123,
      command: {commandName: 'CRITICAL RESPONSE COMMAND'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 3,
      offDuty: 0,
      id: 128,
      command: {commandName: 'HIGHWAY UNIT NO 2'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 132,
      command: {commandName: 'HIGHWAY UNIT NO 1'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 137,
      command: {commandName: 'HOUSING PSA 5'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 143,
      command: {commandName: 'HOUSING PSA 8'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 148,
      command: {commandName: 'NARC BORO BRONX'},
      injuryType: {type: 'Serious Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 153,
      command: {commandName: 'NARC BORO QUEENS NORTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 156,
      command: {commandName: 'NARC BORO QUEENS SOUTH'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 162,
      command: {commandName: 'PBMS SCHOOL SAFETY'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 170,
      command: {commandName: 'TRANSIT BORO BX/QNS TASK FORCE'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 2,
      offDuty: 0,
      id: 176,
      command: {commandName: 'STRATEGIC RESPONSE GROUP'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 181,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 3'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 4,
      offDuty: 0,
      id: 186,
      command: {commandName: 'TRANSIT BUREAU DISTRICT 34'},
      injuryType: {type: 'Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
    {
      onDuty: 1,
      offDuty: 0,
      id: 191,
      command: {commandName: 'PBQS SPECIALIZED UNITS'},
      injuryType: {type: 'Substantial Physical Injury'},
      timeFrame: {year: 2020, quarter: 1},
    },
  ],
}

module.exports = {data}
