const incidentsForceTypeData = [
  {
    year: 2020,
    quarter: 1,
    command: '001 PRECINCT',
    forceCategory: '3-Impact Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '001 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 15,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '001 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '005 DET SQUAD',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '005 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '005 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '005 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '005 SCHOOL SAFETY UNIT',
    forceCategory: '006 DET SQUAD',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '005 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '006 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '006 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 17,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '007 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '007 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '007 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '009 PRECINCT',
    forceCategory: '1-Firearm',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '009 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '009 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 13,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '010 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '010 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '013 PRECINCT',
    forceCategory: '1-Firearm',
    onDuty: 0,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '013 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 0,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '013 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '014 PCT-MIDTOWN SO. PCT',
    forceCategory: '7-Physical Force',
    onDuty: 11,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '017 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '017 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '017 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '018 PCT-MIDTOWN NO. PCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '018 PCT-MIDTOWN NO. PCT',
    forceCategory: '7-Physical Force',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '019 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '019 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 20,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '020 DET SQUAD',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '020 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '020 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '023 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '023 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 26,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '023 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '024 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '024 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '025 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '025 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 18,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '026 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '026 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '028 DET SQUAD',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '028 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '028 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 16,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '030 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 14,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '032 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '032 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 14,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '033 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '033 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 17,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '034 DET SQUAD',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '034 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '034 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 21,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '034 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '040 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '040 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 26,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '041 PRECINCT',
    forceCategory: '1-Firearm',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '041 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '041 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '041 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '042 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '042 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '042 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 26,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '042 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '043 DET SQUAD',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '043 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '043 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 30,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '043 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '044 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 13,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '044 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 46,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '044 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '045 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '045 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '045 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 14,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '046 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '046 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 62,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '047 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 14,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '047 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '047 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 51,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '047 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '048 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '048 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 17,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '049 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '049 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '050 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '052 DET SQUAD',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '052 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '052 PRECINCT',
    forceCategory: '3-Impact Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '5-OC Spray',
    forceCategory: '7-Physical Force',
    onDuty: 23,
    offDuty: 3,
  },
  {
    year: 2020,
    quarter: 1,
    command: '052 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '060 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '060 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 15,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '060 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '061 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '061 PRECINCT',
    forceCategory: '3-Impact Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '061 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 17,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '061 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '062 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '062 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '062 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '063 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '063 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 11,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '066 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '066 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '067 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '067 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 27,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '068 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '068 PRECINCT',
    forceCategory: '3-Impact Weapon',
    onDuty: 0,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '068 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '069 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '069 PRECINCT',
    forceCategory: '6-Restraining Mesh Blanket',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '069 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 11,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '070 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '070 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '070 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 24,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '071 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '071 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 15,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '071 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '072 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '072 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 21,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '073 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '073 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 20,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '075 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 11,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '075 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '075 PRECINCT',
    forceCategory: '6-Restraining Mesh Blanket',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '075 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 33,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '076 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '077 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '077 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '077 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 21,
    offDuty: 2,
  },
  {
    year: 2020,
    quarter: 1,
    command: '078 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '078 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '079 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '079 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '079 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 25,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '081 DET SQUAD',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '081 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '081 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 15,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '083 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '083 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 16,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '084 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '084 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '088 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '088 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 10,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '090 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '090 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 16,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '094 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '094 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '100 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '100 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '101 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '101 PRECINCT',
    forceCategory: '3-Impact Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '101 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 26,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '101ST DET SQUAD',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '102 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '102 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '102 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '102 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '103 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '103 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 45,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '103 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '104 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 13,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '105 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '105 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 18,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '106 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '106 PRECINCT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '106 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '107 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '108 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '109 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '109 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '110 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '110 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 35,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '110 SCHOOL SAFETY UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '111 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '111 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '112 PRECINCT',
    forceCategory: '1-Firearm',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '112 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '112 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '113 PRECINCT',
    forceCategory: '1-Firearm',
    onDuty: 0,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '113 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '113 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 24,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '113TH DET SQUAD',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '114 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 23,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '115 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 13,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '120 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '120 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 33,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '121 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '121 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 15,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '122 PRECINCT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '122 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 10,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '123 PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'BKLYN SPECIAL VICTIMS SQUAD',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'BROOKLYN COURT SECTION',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'CANINE TEAM',
    forceCategory: '4-Police Canine',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'CENTRAL PARK PRECINCT',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'CHIEF OF DEPT INV REVIEW SECT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'CRIMINAL ENTERPRISE INVEST SEC',
    forceCategory: '7-Physical Force',
    onDuty: 0,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'CRITICAL RESPONSE COMMAND',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'DRUG ENFORCEMENT TASK FORCE',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 01',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 02',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 03',
    forceCategory: '2-Electrical Weapon',
    onDuty: 0,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 03',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 05',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 05',
    forceCategory: '7-Physical Force',
    onDuty: 0,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 07',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 07',
    forceCategory: '6-Restraining Mesh Blanket',
    onDuty: 0,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 07',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 08',
    forceCategory: '6-Restraining Mesh Blanket',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 08',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 10',
    forceCategory: '2-Electrical Weapon',
    onDuty: 0,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 10',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV UNIT',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'GANG SQUAD BROOKLYN NORTH',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'GANG SQUAD MANHATTAN NORTH',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'GANG SQUAD MANHATTAN SOUTH',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'GANG SQUAD QUEENS SOUTH',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'GANG SQUAD STATEN ISLAND',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HIGHWAY UNIT NO 1',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HIGHWAY UNIT NO 3',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOMELESS OUT & SHLTR SEC DIV',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOMELESS OUTREACH UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 1',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 1',
    forceCategory: '7-Physical Force',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 2',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 2',
    forceCategory: '7-Physical Force',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 3',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 3',
    forceCategory: '7-Physical Force',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 4',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 4',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 5',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 5',
    forceCategory: '3-Impact Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 5',
    forceCategory: '7-Physical Force',
    onDuty: 16,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 6',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 6',
    forceCategory: '7-Physical Force',
    onDuty: 11,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 7',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 7',
    forceCategory: '7-Physical Force',
    onDuty: 9,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 8',
    forceCategory: '7-Physical Force',
    onDuty: 11,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 9',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 9',
    forceCategory: '7-Physical Force',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'INTEL-CRIMINAL INTEL SECTION',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'INTEL-CRIMINAL INTEL SECTION',
    forceCategory: '3-Impact Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'INTEL-CRIMINAL INTEL SECTION',
    forceCategory: '7-Physical Force',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'MAN COURT SECTION',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'MAN/BX SS ZONE',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BRONX',
    forceCategory: '7-Physical Force',
    onDuty: 10,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BROOKLYN NORTH',
    forceCategory: '2-Electrical Weapon',
    onDuty: 0,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BROOKLYN NORTH',
    forceCategory: '7-Physical Force',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BROOKLYN SOUTH',
    forceCategory: '7-Physical Force',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO MANHATTAN NORTH',
    forceCategory: '7-Physical Force',
    onDuty: 10,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO QUEENS NORTH',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO QUEENS SOUTH',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO QUEENS SOUTH',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO STATEN ISLAND',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'OFFICE CHIEF SPECIAL OPER',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'OTHER',
    forceCategory: '7-Physical Force',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PATROL BORO BRONX',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PATROL BORO BRONX',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PATROL BORO MAN SOUTH',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PATROL BORO MAN SOUTH',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PATROL BORO STATEN ISLAND',
    forceCategory: '2-Electrical Weapon',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PATROL BORO STATEN ISLAND',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PATROL BORO STATEN ISLAND',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBBN SCHOOL SAFETY',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBBS SCHOOL SAFETY',
    forceCategory: '7-Physical Force',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBBX SCHOOL SAFETY',
    forceCategory: '7-Physical Force',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBBX SPECIALIZED UNITS',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBMN SCHOOL SAFETY',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBMS SCHOOL SAFETY',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBQN SCHOOL SAFETY',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBQS SCHOOL SAFETY',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBQS SPECIALIZED UNITS',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBSI SCHOOL SAFETY',
    forceCategory: '7-Physical Force',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'RECRUIT TRAINING SECTION',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'SCHOOL SAFETY DIVISION',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STATEN ISLAND COURT SECTION',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 1 MANHATTAN',
    forceCategory: '7-Physical Force',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 2 BRONX',
    forceCategory: '7-Physical Force',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 3 BROOKLYN',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 4 QUEENS',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 4 QUEENS',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 5 SI',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 5 SI',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESPONSE GROUP',
    forceCategory: '7-Physical Force',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TB ANTI TERRORISM UNIT',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TB ANTI TERRORISM UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BORO BKLN TASK FORCE',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BORO BX/QNS TASK FORCE',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BORO MANH TASK FORCE',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 1',
    forceCategory: '1-Firearm',
    onDuty: 0,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 1',
    forceCategory: '7-Physical Force',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 11',
    forceCategory: '2-Electrical Weapon',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 11',
    forceCategory: '3-Impact Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 11',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 11',
    forceCategory: '7-Physical Force',
    onDuty: 15,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 12',
    forceCategory: '7-Physical Force',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 2',
    forceCategory: '7-Physical Force',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 20',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 20',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 23',
    forceCategory: '7-Physical Force',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 3',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 3',
    forceCategory: '7-Physical Force',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 30',
    forceCategory: '2-Electrical Weapon',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 30',
    forceCategory: '5-OC Spray',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 30',
    forceCategory: '7-Physical Force',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 32',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 32',
    forceCategory: '5-OC Spray',
    onDuty: 0,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 32',
    forceCategory: '7-Physical Force',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 33',
    forceCategory: '3-Impact Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 33',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 33',
    forceCategory: '7-Physical Force',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 34',
    forceCategory: '2-Electrical Weapon',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 34',
    forceCategory: '7-Physical Force',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 4',
    forceCategory: '2-Electrical Weapon',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 4',
    forceCategory: '5-OC Spray',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 4',
    forceCategory: '7-Physical Force',
    onDuty: 15,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRB BROOKLYN TRAFFIC ENF UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRB MANHATTAN TOW POUND UNIT',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRB SOUTH INTERSECTION CONTROL',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRB TRAFF SPECIAL OPS SECTION',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'VICE ENFORCEMENT DIV ZONE 2',
    forceCategory: '7-Physical Force',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'WARRANT SECTION',
    forceCategory: '2-Electrical Weapon',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'WARRANT SECTION',
    forceCategory: '7-Physical Force',
    onDuty: 17,
    offDuty: 0,
  },
]

module.exports = {incidentsForceTypeData}
