const officerInjury = [
  {
    year: 2020,
    quarter: 1,
    command: '001 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '005 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '006 DET SQUAD',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '006 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '006 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 10,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '007 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '009 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '010 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '013 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '014 PCT-MIDTOWN SO. PCT',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '017 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '017 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '018 PCT-MIDTOWN NO. PCT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '019 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '019 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 11,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '020 DET SQUAD',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '020 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '020 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '020 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '023 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 15,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '024 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '024 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '025 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '026 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '028 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '028 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 10,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '028 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '030 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '032 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '033 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 16,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '033 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '034 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '040 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '040 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 20,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '041 PRECINCT',
    officerInjury: '4 MOS Killed or Shot',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '041 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '042 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '042 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '043 DET SQUAD',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '043 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '043 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '043 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '044 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '044 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 19,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '045 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '045 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '046 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '046 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 20,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '047 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '047 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 14,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '047 SCHOOL SAFETY UNIT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '047 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '048 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '048 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '049 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '049 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '050 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '050 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '052 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '052 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 12,
    offDuty: 4,
  },
  {
    year: 2020,
    quarter: 1,
    command: '052 SCHOOL SAFETY UNIT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '060 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '060 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '061 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 10,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '061 SCHOOL SAFETY UNIT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '061 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '062 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '063 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '063 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '066 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '067 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 10,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '068 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 17,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '069 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '070 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 0,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '070 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 13,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '071 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '071 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '072 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 11,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '073 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '073 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '073 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '075 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '075 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '075 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 19,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '076 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '077 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 13,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '078 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '079 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '079 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '081 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '083 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '084 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '084 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '088 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '090 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '094 DET SQUAD',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '094 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '100 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '100 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '101 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '101ST DET SQUAD',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '102 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '102 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '103 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '103 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '103 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 19,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '103 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '104 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '105 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '106 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '107 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '108 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '109 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '110 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '110 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '110 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '111 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '111 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '112 SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '113 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '113 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 14,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '113TH DET SQUAD',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '114 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 13,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '115 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '115TH DET SQUAD',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '120 PRECINCT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '120 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 13,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '121 PRECINCT',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '121 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '122 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '123 PRECINCT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'BRONX COURT SECT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'BROOKLYN COURT SECTION',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'CANINE TEAM',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'CHIEF OF DEPT INV REVIEW SECT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'DET BORO BX HOMICIDE SQ',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'DRUG ENFORCEMENT TASK FORCE',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 08',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 10',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'GANG SQUAD MANHATTAN SOUTH',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'GRAND LARCENY DIVISION',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'GRAND LARCENY DIVISION',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HIGHWAY UNIT NO 2',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HIGHWAY UNIT NO 3',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOMELESS OUTREACH UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 1',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 2',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 4',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 5',
    officerInjury: '1 Physical Injury',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 6',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 6',
    officerInjury: '1 Physical Injury',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 7',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 7',
    officerInjury: '1 Physical Injury',
    onDuty: 13,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 8',
    officerInjury: '1 Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 9',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'INTEL-CRIMINAL INTEL SECTION',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'MAN/BX SS ZONE',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'MTN SCHOOL SAFETY UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BRONX',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BRONX',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BROOKLYN NORTH',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BROOKLYN SOUTH',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO QUEENS NORTH',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'OFFICE CHIEF SPECIAL OPER',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'P C O LIAISON UNIT',
    officerInjury: '4 MOS Killed or Shot',
    onDuty: 0,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PATROL BORO STATEN ISLAND',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBBN SCHOOL SAFETY',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBBN SCHOOL SAFETY',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBBN SPECIALIZED UNITS',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBBS SCHOOL SAFETY',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBBX SCHOOL SAFETY',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBMN SCHOOL SAFETY',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBQN SCHOOL SAFETY',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBQS SCHOOL SAFETY',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBSI SCHOOL SAFETY',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'QNS COURT SECTION',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 1 MANHATTAN',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 2 BRONX',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 3 BROOKLYN',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 4 QUEENS',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TB ANTI TERRORISM UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BORO BKLN TASK FORCE',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BORO BX/QNS TASK FORCE',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BORO MANH TASK FORCE',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 1',
    officerInjury: '4 MOS Killed or Shot',
    onDuty: 0,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 1',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 11',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 11',
    officerInjury: '1 Physical Injury',
    onDuty: 18,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 12',
    officerInjury: '2 Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 12',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 2',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 2',
    officerInjury: '1 Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 20',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 23',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 3',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 30',
    officerInjury: '1 Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 32',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 33',
    officerInjury: '1 Physical Injury',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 34',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 4',
    officerInjury: '1 Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRB BRONX TRAFFIC ENF UNIT',
    officerInjury: '3 Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRB BRONX TRAFFIC ENF UNIT',
    officerInjury: '1 Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRB MANHATTAN SUMMONS ENF SEC',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'VICE ENFORCEMENT DIV ZONE 2',
    officerInjury: '1 Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'WARRANT SECTION',
    officerInjury: '1 Physical Injury',
    onDuty: 12,
    offDuty: 0,
  },
]

module.exports = {officerInjury}
