const subjectInjuryData = [
  {
    year: 2020,
    quarter: 1,
    command: '001 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '001 SCHOOL SAFETY UNIT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '006 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '006 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '006 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '007 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '009 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '009 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '010 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '013 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '014 PCT-MIDTOWN SO. PCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '017 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '017 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '018 PCT-MIDTOWN NO. PCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '018 PCT-MIDTOWN NO. PCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '019 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '020 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '020 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '023 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '024 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '025 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '026 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '028 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '028 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '028 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '030 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '030 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '032 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '032 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '032 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '033 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '034 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '034 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '034 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 11,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '040 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '041 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: '041 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '042 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '042 SCHOOL SAFETY UNIT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '043 DET SQUAD',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '043 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 12,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '044 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '044 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 22,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '045 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '046 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '046 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 18,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '047 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '047 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 29,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '048 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '048 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '050 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '052 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '052 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 10,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '060 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '060 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '060 SCHOOL SAFETY UNIT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '061 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '062 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '062 SCHOOL SAFETY UNIT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '063 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '066 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '067 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '068 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '069 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '069 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '070 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '070 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '071 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '072 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '072 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '073 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '073 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '073 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '075 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '075 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '075 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 29,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '076 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '077 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 11,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '078 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '079 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '079 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 15,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '081 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '081 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '083 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '083 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '084 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '088 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '088 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '090 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '090 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '094 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '100 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '101 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '101 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 9,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '102 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '103 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 19,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '104 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '104 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '105 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '105 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 8,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '106 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '106 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '108 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '109 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '110 PRECINCT',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '110 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '110 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '111 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '112 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '113 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '114 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '115 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '120 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 13,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '121 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 6,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '122 PRECINCT',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '122 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 7,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: '123 PRECINCT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'BKLYN SPECIAL VICTIMS SQUAD',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'BRONX ROBBERY SQUAD',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'BROOKLYN COURT SECTION',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'CANINE TEAM',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'CRITICAL RESPONSE COMMAND',
    subjectInjury: '3-Physical Injury',
    onDuty: 0,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'DRUG ENFORCEMENT TASK FORCE',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 02',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 03',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV SQ 05',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'EMER SERV UNIT',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'GANG SQUAD BROOKLYN NORTH',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'GANG SQUAD MANHATTAN SOUTH',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HIGHWAY UNIT NO 1',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HIGHWAY UNIT NO 2',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HIGHWAY UNIT NO 3',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HIGHWAY UNIT NO.5',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 1',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 2',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 3',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 4',
    subjectInjury: '3-Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 5',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 5',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 6',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 6',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 7',
    subjectInjury: '3-Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 8',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'HOUSING PSA 9',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'INTEL-CRIMINAL INTEL SECTION',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'INTEL-CRIMINAL INTEL SECTION',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'MAN/BX SS ZONE',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BRONX',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BRONX',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BRONX',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BROOKLYN NORTH',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO BROOKLYN SOUTH',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO MANHATTAN NORTH',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO QUEENS NORTH',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO QUEENS SOUTH',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'NARC BORO STATEN ISLAND',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'OFFICE CHIEF SPECIAL OPER',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'OTHER',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PATROL BORO MAN SOUTH',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PATROL BORO STATEN ISLAND',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBMS SCHOOL SAFETY',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBQN SPECIALIZED UNITS',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBQS SCHOOL SAFETY',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBQS SPECIALIZED UNITS',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'PBQS SPECIALIZED UNITS',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 1 MANHATTAN',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 2 BRONX',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 2 BRONX',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 3 BROOKLYN',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 4 QUEENS',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 1,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESP GRP 5 SI',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'STRATEGIC RESPONSE GROUP',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BORO BX/QNS TASK FORCE',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BORO MANH TASK FORCE',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 11',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 11',
    subjectInjury: '3-Physical Injury',
    onDuty: 5,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 12',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 2',
    subjectInjury: '3-Physical Injury',
    onDuty: 2,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 20',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 3',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 3',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 30',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 32',
    subjectInjury: '2-Substantial Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 32',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 33',
    subjectInjury: '3-Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 34',
    subjectInjury: '3-Physical Injury',
    onDuty: 4,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRANSIT BUREAU DISTRICT 4',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRB BROOKLYN TRAFFIC ENF UNIT',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'TRB CITYWIDE TRAFFIC T/F',
    subjectInjury: '3-Physical Injury',
    onDuty: 1,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'WARRANT SECTION',
    subjectInjury: '1-Serious Physical Injury',
    onDuty: 3,
    offDuty: 0,
  },
  {
    year: 2020,
    quarter: 1,
    command: 'WARRANT SECTION',
    subjectInjury: '3-Physical Injury',
    onDuty: 5,
    offDuty: 1,
  },
]

module.exports = {subjectInjuryData}
